"""Build a self-contained Kaggle Orbit Wars submission.

Kaggle agent submissions are easiest to reason about as one Python file. This
script bundles the heuristic stack and appends a safe `agent(obs, config=None)`
entrypoint so Kaggle's optional configuration argument cannot be mistaken for
the heuristic's `max_moves` parameter.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parent
OUT = ROOT / "submission.py"

SOURCES = [
    ("action_space.py", ROOT / "orbit_wars/core/action_space.py"),
    ("radar.py", ROOT / "orbit_wars/core/radar.py"),
    ("targeting.py", ROOT / "orbit_wars/core/targeting.py"),
    ("harness.py", ROOT / "orbit_wars/legacy/harness.py"),
    ("agents.py", ROOT / "orbit_wars/legacy/agents.py"),
]


def _strip_local_imports(text: str) -> str:
    out: list[str] = []
    skipping_harness_import = False

    for line in text.splitlines():
        stripped = line.strip()

        if skipping_harness_import:
            if stripped == ")":
                skipping_harness_import = False
            continue

        if stripped.startswith("from __future__ import "):
            continue
        if stripped == "from radar import Radar":
            continue
        if stripped == "from radar import Radar, RadarHit":
            continue
        if stripped == "import targeting as T":
            continue
        if stripped == "from action_space import MAX_MODEL_MOVES":
            continue
        if stripped == "from harness import (":
            skipping_harness_import = True
            continue

        out.append(line)

    return "\n".join(out).rstrip() + "\n"


def build() -> str:
    parts = [
        "# Generated by make_submission.py. Do not edit by hand.\n",
        "from __future__ import annotations\n\n",
    ]

    for name, path in SOURCES:
        source = path.read_text()
        parts.append(f"\n# --- {name} ---\n")
        parts.append(_strip_local_imports(source))

        if name == "targeting.py":
            parts.append(
                "\n"
                "class _TargetingNamespace:\n"
                "    pass\n\n"
                "T = _TargetingNamespace()\n"
                "T.fleet_speed = fleet_speed\n"
                "T.future_position = future_position\n"
            )

    parts.append(
        "\n"
        "# --- Kaggle entrypoint ---\n"
        "def agent(obs, config=None):\n"
        "    return heuristic_agent(obs, max_moves=MAX_MODEL_MOVES)\n"
    )
    return "".join(parts)


def main() -> None:
    OUT.write_text(build())
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
